export const exportToHtml = (
  previewContent: string,
  theme: 'light' | 'dark',
  filename: string = 'document'
): void => {
  const html = `<!DOCTYPE html>
<html lang="en" data-theme="${theme}">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${filename}</title>
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/katex@0.16.0/dist/katex.min.css">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.8.0/styles/github${theme === 'dark' ? '-dark' : ''}.min.css">
  <style>
    :root {
      --bg: ${theme === 'dark' ? '#1a1a1a' : '#ffffff'};
      --text: ${theme === 'dark' ? '#e5e5e5' : '#1a1a1a'};
      --code-bg: ${theme === 'dark' ? '#2d2d2d' : '#f5f5f5'};
    }
    * {
      margin: 0;
      padding: 0;
      box-sizing: border-box;
    }
    body {
      max-width: 900px;
      margin: 0 auto;
      padding: 40px 20px;
      font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif;
      line-height: 1.7;
      color: var(--text);
      background: var(--bg);
    }
    h1, h2, h3, h4, h5, h6 {
      margin-top: 24px;
      margin-bottom: 16px;
      font-weight: 600;
      line-height: 1.25;
    }
    h1 { font-size: 2em; border-bottom: 1px solid ${theme === 'dark' ? '#333' : '#eee'}; padding-bottom: 8px; }
    h2 { font-size: 1.5em; }
    h3 { font-size: 1.25em; }
    p { margin-bottom: 16px; }
    code {
      background: var(--code-bg);
      padding: 2px 6px;
      border-radius: 3px;
      font-family: 'Courier New', monospace;
      font-size: 0.9em;
    }
    pre {
      background: var(--code-bg);
      padding: 16px;
      border-radius: 6px;
      overflow-x: auto;
      margin-bottom: 16px;
    }
    pre code {
      background: none;
      padding: 0;
    }
    blockquote {
      border-left: 4px solid ${theme === 'dark' ? '#555' : '#ddd'};
      padding-left: 16px;
      margin: 16px 0;
      color: ${theme === 'dark' ? '#aaa' : '#666'};
    }
    table {
      border-collapse: collapse;
      width: 100%;
      margin: 16px 0;
    }
    th, td {
      border: 1px solid ${theme === 'dark' ? '#444' : '#ddd'};
      padding: 8px 12px;
      text-align: left;
    }
    th {
      background: ${theme === 'dark' ? '#2d2d2d' : '#f5f5f5'};
      font-weight: 600;
    }
    a {
      color: ${theme === 'dark' ? '#58a6ff' : '#0969da'};
      text-decoration: none;
    }
    a:hover {
      text-decoration: underline;
    }
    img {
      max-width: 100%;
      height: auto;
    }
    .mermaid {
      display: flex;
      justify-content: center;
      margin: 24px 0;
    }
    ul, ol {
      margin-bottom: 16px;
      padding-left: 24px;
    }
    li {
      margin-bottom: 4px;
    }
  </style>
</head>
<body>
  ${previewContent}
  <footer style="margin-top: 60px; padding-top: 20px; border-top: 1px solid ${theme === 'dark' ? '#333' : '#eee'}; text-align: center; font-size: 0.9em; color: ${theme === 'dark' ? '#666' : '#999'};">
    Generated by MDBuild.io
  </footer>
</body>
</html>`;

  const blob = new Blob([html], { type: 'text/html;charset=utf-8' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = `${filename}_${Date.now()}.html`;
  a.click();
  URL.revokeObjectURL(url);
};
